# Generated by Django 5.0.6 on 2024-06-08 16:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان')),
                ('text', models.TextField(verbose_name='نوشته')),
                ('group', models.BooleanField(default=False, verbose_name='مرحله گروهی')),
                ('knockout', models.BooleanField(default=False, verbose_name='مرحله حذفی')),
                ('semiFinal', models.BooleanField(default=False, verbose_name='مرحله نیمه نهایی')),
                ('final', models.BooleanField(default=False, verbose_name='مرحله فینال')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('first_match_start', models.TimeField(verbose_name='زمان شروع اولین مسابقه')),
            ],
            options={
                'verbose_name': 'مسابقه',
                'verbose_name_plural': 'مسابقات',
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_name', models.CharField(default=' ', max_length=100)),
                ('away_name', models.CharField(default=' ', max_length=100)),
                ('home', models.CharField(blank=True, max_length=2, null=True, verbose_name='تعداد گل میزبان')),
                ('home_img', models.ImageField(blank=True, null=True, upload_to='images', verbose_name='تصویر میزبان')),
                ('away', models.CharField(blank=True, max_length=2, null=True, verbose_name='تعداد گل میهمان')),
                ('away_img', models.ImageField(blank=True, null=True, upload_to='images', verbose_name='تصویر میهمان')),
                ('matchday', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='HomeApp.matchday', verbose_name='روز بازی')),
            ],
            options={
                'verbose_name': 'بازی',
                'verbose_name_plural': 'بازیها',
            },
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(default=0, verbose_name='امتیاز')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'امتیاز',
                'verbose_name_plural': 'امتیازات',
            },
        ),
        migrations.CreateModel(
            name='UserForcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_name', models.CharField(default=' ', max_length=100)),
                ('away_name', models.CharField(default=' ', max_length=100)),
                ('home', models.CharField(max_length=2, verbose_name='تعداد گل میزبان')),
                ('home_img', models.ImageField(blank=True, null=True, upload_to='images', verbose_name='تصویر میزبان')),
                ('away', models.CharField(max_length=2, verbose_name='تعداد گل میهمان')),
                ('away_img', models.ImageField(blank=True, null=True, upload_to='images', verbose_name='تصویر میهمان')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forcast', to='HomeApp.match', verbose_name='بازی')),
                ('matchday', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forcast', to='HomeApp.matchday', verbose_name='روز بازی')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forcast', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'پیش بینی',
                'verbose_name_plural': 'پیش بینی ها',
            },
        ),
    ]
