# Generated by Django 5.0.6 on 2024-06-12 12:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeApp', '0002_rule'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserForcastHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_name', models.CharField(default=' ', max_length=100)),
                ('away_name', models.CharField(default=' ', max_length=100)),
                ('home', models.CharField(max_length=2, verbose_name='تعداد گل میزبان')),
                ('home_img', models.ImageField(blank=True, null=True, upload_to='images', verbose_name='تصویر میزبان')),
                ('away', models.CharField(max_length=2, verbose_name='تعداد گل میهمان')),
                ('away_img', models.ImageField(blank=True, null=True, upload_to='images', verbose_name='تصویر میهمان')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='HomeApp.match', verbose_name='بازی')),
                ('matchday', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='HomeApp.matchday', verbose_name='روز بازی')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'تاربخچه پیش بینی',
                'verbose_name_plural': ' تاربخچه پیش بینی ها',
            },
        ),
    ]
